export const TICKET_INFO = 'TICKET_INFO'
export const IF_REFESH = 'IF_REFESH'
export const STAT_DAY = 'STAT_DAY'
export const SYN_DAY = 'SYN_DAY'
export const DCT = 'DCT'
export const TRUNCATE_DCT_COMMON_INFO = 'TRUNCATE_DCT_COMMON_INFO'

export const STAT_DAY_SET_PROPERTY_BY_KEY = 'STAT_DAY_SET_PROPERTY_BY_KEY'
export const TICKET_SET_PROPERTY_BY_KEY = 'TICKET_SET_PROPERTY_BY_KEY'

export const SET_STAT_HEADER_DYNAMIC = 'SET_STAT_HEADER_DYNAMIC'
export const TRUNCATE_STAT_DAY_DATA = 'TRUNCATE_STAT_DAY_DATA'
export const INIT_STAT_HEADER_COLUMN = 'INIT_STAT_HEADER_COLUMN'

export const SET_SYN_HEADER_DYNAMIC = 'SET_SYN_HEADER_DYNAMIC'
export const TRUNCATE_SYN_DAY_DATA = 'TRUNCATE_SYN_DAY_DATA'
export const SYN_OPEN_PERIOD = 'SYN_OPEN_PERIOD'

export const TRUNCATE_TICKET_INFO = 'TRUNCATE_TICKET_INFO'

export const SET_PERIOD_COLUMNS_LIST = 'SET_PERIOD_COLUMNS_LIST'
export const SET_PERIOD_TABLE_DATA = 'SET_PERIOD_TABLE_DATA'

export const GET_CURRENT_SITE = 'GET_CURRENT_SITE'
export const PRIVILEGES_INFO = 'PRIVILEGES_INFO'
export const SHOW_ORDER_INFO = 'SHOW_ORDER_INFO'
export const SHOW_TICKET_INFO = 'SHOW_TICKET_INFO'
export const SOURCE = 'SOURCE'
export const GET_CURRENT_QUEUE = 'GET_CURRENT_QUEUE'
export const TRUNCATE_SOURCE_DATA = 'TRUNCATE_SOURCE_DATA'

export const MODAL_BODY_INFO = 'MODAL_BODY_INFO'
export const CURRENT_BODY = 'CURRENT_BODY'
export const TRUNCATE_BODY_INFO = 'TRUNCATE_BODY_INFO'

export const DCT_CONFIG = 'DCT_CONFIG'
export const MODAL_ADD_LATI = 'MODAL_ADD_LATI'
export const ADD_DCT_CONFIG = 'ADD_DCT_CONFIG'
export const SET_DCT_CONFIG = 'SET_DCT_CONFIG'
export const TRUNCATE_CONFIG_DATA = 'TRUNCATE_CONFIG_DATA'

// 统计分析部分
export const CUSTOMER_FLOW = 'CUSTOMER_FLOW'
export const CUSTOMER_FLOW_DCT = 'CUSTOMER_FLOW_DCT'
export const CUSTOMER_FLOW_OPTION = 'CUSTOMER_FLOW_OPTION'
export const INIT_ANALYSIS_PROPERTY = 'INIT_ANALYSIS_PROPERTY'

export const AGE_GENDER_OPTION = 'AGE_GENDER_OPTION'
export const AGE_GENDER = 'AGE_GENDER'

export const AGE_OPTION = 'AGE_OPTION'
export const AGE = 'AGE'

export const GENDER_OPTION = 'GENDER_OPTION'
export const GENDER = 'GENDER'

export const DIRECT_OTA = 'DIRECT_OTA'
export const DIRECT_OTA_OPTION = 'DIRECT_OTA_OPTION'

export const DIRECT = 'DIRECT'
export const DIRECT_OPTION = 'DIRECT_OPTION'

export const OTA = 'OTA'
export const OTA_OPTION = 'OTA_OPTION'

export const AGENCY_PERSON_OPTION = 'AGENCY_PERSON_OPTION'
export const AGENCY_PERSON = 'AGENCY_PERSON'

export const AGENCY_OPTION = 'AGENCY_OPTION'
export const AGENCY = 'AGENCY'

export const PAY_CHANNEL_OPTION = 'PAY_CHANNEL_OPTION'
export const PAY_CHANNEL = 'PAY_CHANNEL'

export const SELLER_OPTION = 'SELLER_OPTION'
export const SELLER = 'SELLER'

export const COUPON_OPTION = 'COUPON_OPTION'
export const COUPON = 'COUPON'

export const LOCK_MEDIUM_OPTION = 'LOCK_MEDIUM_OPTION'
export const LOCK_MEDIUM = 'LOCK_MEDIUM'

export const TICKET_TIME_OPTION = 'TICKET_TIME_OPTION'
export const TICKET_TIME = 'TICKET_TIME'

export const USER_FLOW_HISTORY_OPTION = 'USER_FLOW_HISTORY_OPTION'
export const USER_FLOW_HISTORY = 'USER_FLOW_HISTORY'

export const REFUND_ABNORMAL_OPTION = 'REFUND_ABNORMAL_OPTION'
export const REFUND_ABNORMAL = 'REFUND_ABNORMAL'

export const TICKETS_KIND_OPTION = 'TICKETS_KIND_OPTION'
export const TICKETS_KIND = 'TICKETS_KIND'

export const SALE_USE_PERIOD_OPTION = 'SALE_USE_PERIOD_OPTION'
export const SALE_USE_PERIOD = 'SALE_USE_PERIOD'

export const REPEAT_OPTION = 'REPEAT_OPTION'
export const REPEAT = 'REPEAT'

export const ATTR_PLACE_OPTION = 'ATTR_PLACE_OPTION'
export const ATTR_PLACE = 'ATTR_PLACE'

export const APPOINTMENT_OPTION = 'APPOINTMENT_OPTION'
export const APPOINTMENT = 'APPOINTMENT'

// home
export const DIMENSIONALITY = 'DIMENSIONALITY'
export const HOME_PAY_OPTION = 'HOME_PAY_OPTION'
export const TICKET_KIND_OPTION = 'TICKET_KIND_OPTION'
export const VISITOR_OPTION = 'VISITOR_OPTION'

export const AHEAD_OPTION = 'AHEAD_OPTION'
export const AHEAD = 'AHEAD'

export const SECOND_INCOME_OPTION = 'SECOND_INCOME_OPTION'
export const SECOND_INCOME = 'SECOND_INCOME'

export const MAIN_CUSTOMERS_NUM = 'MAIN_CUSTOMERS_NUM'
export const MAIN_CUSTOMERS_NUM_DATA = 'MAIN_CUSTOMERS_NUM_DATA'

export const TIMEZONE_OPTION = 'TIMEZONE_OPTION'
export const TIMEZONE = 'TIMEZONE'

export const THERMA_OPTION = 'THERMA_OPTION'
export const NORTH_OPTION = 'NORTH_OPTION'
export const WEST_OPTION = 'WEST_OPTION'
export const SOUTH_OPTION = 'SOUTH_OPTION'

export const IN_SEVEN_DAYS_OPTION = 'IN_SEVEN_DAYS_OPTION'
export const IN_SEVEN_DAYS = 'IN_SEVEN_DAYS'
