import * as mapData from './map-data'

// 定义省份地图数据
const cityMap = {
  '中国': mapData.zhongguo,
  '上海': mapData.shanghai,
  '河北': mapData.hebei,
  '山西': mapData.shangxi,
  '内蒙古': mapData.neimenggu,
  '辽宁': mapData.liaoning,
  '吉林': mapData.jilin,
  '黑龙江': mapData.heilongjiang,
  '江苏': mapData.jiangsu,
  '浙江': mapData.zhejiang,
  '安徽': mapData.anhui,
  '福建': mapData.fujian,
  '江西': mapData.jiangxi,
  '山东': mapData.shandong,
  '河南': mapData.henan,
  '湖北': mapData.hubei,
  '湖南': mapData.hunan,
  '广东': mapData.guangdong,
  '广西': mapData.guangxi,
  '海南': mapData.hainan,
  '四川': mapData.sichuan,
  '贵州': mapData.guizhou,
  '云南': mapData.yunnan,
  '西藏': mapData.xizang,
  '陕西': mapData.shanxi,
  '甘肃': mapData.gansu,
  '青海': mapData.qinghai,
  '宁夏': mapData.ningxia,
  '新疆': mapData.xinjiang,
  '北京': mapData.beijing,
  '天津': mapData.tianjin,
  '重庆': mapData.chongqing,
  '香港': mapData.xianggang,
  '澳门': mapData.aomen
}
// 城市对应拼音
const cityToPinyin = {
  '中国': 'zhongguo',
  '上海': 'shanghai',
  '河北': 'hebei',
  '山西': 'shangxi',
  '内蒙古': 'neimenggu',
  '辽宁': 'liaoning',
  '吉林': 'jilin',
  '黑龙江': 'heilongjiang',
  '江苏': 'jiangsu',
  '浙江': 'zhejiang',
  '安徽': 'anhui',
  '福建': 'fujian',
  '江西': 'jiangxi',
  '山东': 'shandong',
  '河南': 'henan',
  '湖北': 'hubei',
  '湖南': 'hunan',
  '广东': 'guangdong',
  '广西': 'guangxi',
  '海南': 'hainan',
  '四川': 'sichuan',
  '贵州': 'guizhou',
  '云南': 'yunnan',
  '西藏': 'xizang',
  '陕西': 'shanxi',
  '甘肃': 'gansu',
  '青海': 'qinghai',
  '宁夏': 'ningxia',
  '新疆': 'xinjiang',
  '北京': 'beijing',
  '天津': 'tianjin',
  '重庆': 'chongqing',
  '香港': 'xianggang',
  '澳门': 'aomen'
}

export { cityMap, cityToPinyin }
